# Generated by Django 3.2.4 on 2021-11-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
