# Generated by Django 3.2.4 on 2021-11-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_address1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
